catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedBooksListView.as_view(), name='borrowed'),
    path('books/<pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('author/<pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('book/<uuid:pk>/renew/', views.BookInstanceUpdateView.as_view(), name='renew'),
]

elf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('catalog/', include('catalog.urls')),
    path('members/', include('members.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [
    path('register/', views.MyRegisterView.as_view(), name='register'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <title>
        {% block title %}One Library!{% endblock %}
    </title>
  </head>
  <body>

    <!-- Navbar -->
    {% include 'navbar.html' %}

    <!-- Contents block -->
    <div class="container">
    </br>

        <!-- messages -->
        {% if messages %}
        {% for  msg in messages %}
        <div class="alert alert-{{ msg.tags }} alert-dismissible fade show" role="alert">
          {{ msg }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
        {% endif %}
        
        {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
        {% block content %}{% endblock %}
    </div>



      <!-- My Pagination Bootstrap Django Html Code -->
      {% if is_paginated %}
      <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page=1" tabindex="-1">&laquo; first</a>
              </li>
              <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                  <a class="page-link"
                      href="?page={{ page_obj.previous_page_number }}"
                      tabindex="-1">Previous</a>
              </li>
              <li class="page-item""><a class=" page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
              {% endif %}
              <li class="page-item active">
                  <span class="page-link">
                      {{ page_obj.number }}
                      <span class="sr-only">(current)</span>
                  </span>
              </li>
              {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{% if page_obj.has_next %}{{ page_obj.next_page_number }}{% else %}...{% endif %}</a></li>
              <li class="page-item">
                  <a class="page-link"
                      href="?page={{ page_obj.next_page_number }}">Next</a>
              </li>
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
              </li>
              {% endif %}
          </ul>
      </nav>
      {% endif %}
 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
Hello {{ user|title }}
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'catalog:index' %}">Library<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:books' %}">All Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:authors' %}">All Authors</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Add..
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Author</a>
            <a class="dropdown-item" href="#">Book</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">---</a>
          </div>
        </li>

        
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Members
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'members:register' %}">Register</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>

        
      </ul>

      <ul class="navbar-nav ">
      {% if request.user.is_authenticated %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user|title }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'catalog:my-borrowed' %}">My Borrowed</a>
          {% if request.user.is_staff %}
          <a class="dropdown-item" href="{% url 'catalog:borrowed' %}">All Borrowed</a>
          {% endif %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      {% endif %} 
      </ul>

      <form action="" method="post" class="form-inline my-2 my-lg-0">
        {% csrf_token %}
        <input name='searched' class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>